const officeKey = {
  montreal: "montreal",
  pointeclaire: "pointeclaire",
  saintlaurent: "saintlaurent",
  laval: "laval",
};

const officeKeyDisplayName = {
  montreal: "Montréal",
  pointeclaire: "Pointe Claire",
  saintlaurent: "Saint-Laurent",
  laval: "Laval",
};

module.exports = {
  officeKey,
  officeKeyDisplayName,
  twitter: {
    appKey: process.env.TWITTER_APP_KEY || "",
    appSecret: process.env.TWITTER_APP_SECRET || "",
    accessToken: process.env.TWITTER_APP_ACCESS_TOKEN || "",
    accessSecret: process.env.TWITTER_APP_ACCESS_SECRET || "",
    accounts: {
      // Generated by 'export $(cat .env | xargs) && node eservice-canada-bot/libs/twitter.js'
      [officeKey.montreal]: {
        accessToken: process.env.TWITTER_APP_MONTREAL_ACCESS_TOKEN || "",
        accessSecret: process.env.TWITTER_APP_MONTREAL_ACCESS_SECRET || "",
      },
      [officeKey.pointeclaire]: {
        accessToken: process.env.TWITTER_APP_POINTECLAIRE_ACCESS_TOKEN || "",
        accessSecret: process.env.TWITTER_APP_POINTECLAIRE_ACCESS_SECRET || "",
      },
      [officeKey.saintlaurent]: {
        accessToken: process.env.TWITTER_APP_SAINTLAURENT_ACCESS_TOKEN || "",
        accessSecret: process.env.TWITTER_APP_SAINTLAURENT_ACCESS_SECRET || "",
      },
      [officeKey.laval]: {
        accessToken: process.env.TWITTER_APP_LAVAL_ACCESS_TOKEN || "",
        accessSecret: process.env.TWITTER_APP_LAVAL_ACCESS_SECRET || "",
      },
    },
  },
  eservice: {
    bookingUrl: "https://eservices.canada.ca/en/reservation/application/?booking-privacy=true",
    getTimeSlotsUrl: "https://eservice-api-production.azurewebsites.net/api/GetAvailableTimeslots",
    bookingServiceOfferingIds: "57af4796-67ab-ea11-a812-000d3af4f03d", // Passport service
    languageOptionsKey: "french",
    bookingTypeOptionsKey: "passport service",
    earliestTravelDateRangeOptionsKey: "travel between 6 and 45 business days",
    officeIds: {
      [officeKey.montreal]: "2f0a32f7-bcac-ea11-a812-000d3af4316a",
      [officeKey.pointeclaire]: "2d0a32f7-bcac-ea11-a812-000d3af4316a",
      [officeKey.saintlaurent]: "290a32f7-bcac-ea11-a812-000d3af4316a",
      [officeKey.laval]: "310a32f7-bcac-ea11-a812-000d3af4316a",
    },
  },
};
